### ISSUE TITLE
fix hardcoded reference to home directory

### ISSUE THREAD

**Issue by Deepidoo** [Imrvrs/nvim#17]
Thanks for the config.

I had to remove the references to you home directory in lua/utils.lua

replacing
`"/home/yujiqo/.config/nvim/lua/__colorscheme__.json"`
by
`os.getenv("HOME").."/.config/nvim/lua/__colorscheme__.json"`

**Comment by yujiqo** [comment]
sorry, I've just seen the issue. I removed this feature recently btw
